# Generated by Django 6.1.1 on 2026-10-06 00:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Planta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Mínimo 3 caracteres.",
                        max_length=80,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="nombre",
                    ),
                ),
                ("especie", models.CharField(max_length=120, verbose_name="especie")),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="notas de cuidado"),
                ),
                (
                    "frecuencia_riego_dias",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Entre 1 y 365 días.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="riego cada (días)",
                    ),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(verbose_name="fecha de adquisición"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        choices=[
                            ("INT", "Interior"),
                            ("EXT", "Exterior"),
                            ("BAL", "Balcón"),
                        ],
                        default="INT",
                        max_length=3,
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "es_toxica",
                    models.BooleanField(
                        default=False, verbose_name="tóxica para mascotas"
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "planta",
                "verbose_name_plural": "plantas",
                "ordering": ["-creada_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("propietario", "nombre"),
                        name="planta_nombre_unico_por_usuario",
                        violation_error_message="Ya tienes una planta con ese nombre.",
                    )
                ],
            },
        ),
    ]
